### ISSUE TITLE
Boundary check for device data failed Error: Error checking type.

### ISSUE THREAD

**Issue by philthetank** [lstrojny/homebridge-prometheus-exporter#19]
I saw you mention this on r/homebridge and had to try it. I'm hoping to record thermostat runtime and temperature from the various sensors I have in homebridge. 

**Describe The Bug:**

I see errors in the logs every service refresh interval and fewer metrics (no temperature metrics) available under `/metrics` than expected. I'm assuming the error prevents more metrics from being emitted. 

**To Reproduce:**

Install plugin, use default settings, set as child bridge, restart, then view logs.

**Expected behavior:**

No errors in the logs 

**Logs:**

Here's the first part of many of the errors the from the log with a little manual formatting and pretty print

```
[invalid_union] Invalid input at path "accessories.accessories.[12].services.[1].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[1].characteristics.[0]" is 

{
    "type": "00000073-0000-1000-8000-0026BB765291",
    "iid": 11,
    "value": null,
    "perms": [
        "ev",
        "pr"
    ],
    "description": "Programmable Switch Event",
    "format": "uint8",
    "minValue": 0,
    "maxValue": 2,
    "minStep": 1,
    "valid-values": [
        0
    ]
}
```

Here's the error before it prints another 4000 lines of accessory json. I imagine all` the useful information is included in the error text but I can post the accessory json if that's useful.

```
[11/11/2022, 7:35:14 PM] [homebridge-prometheus-exporter] Boundary check for device data failed Error: Error checking type. Details: [invalid_union] Invalid input at path "accessories.accessories.[12].services.[1].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[1].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":11,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":15,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":19,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":23,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":27,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[23].services.[1].characteristics.[0]" (data at resolved path "accessories.accessories.[23].services.[1].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":11,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}")
    at checkBoundary (/usr/local/lib/node_modules/homebridge-prometheus-exporter/src/boundaries/checker.ts:51:11)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-prometheus-exporter/src/adapters/discovery/hap_node_js_client.ts:34:51)
    at HAPNodeJSClient.emit (node:events:390:28)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-prometheus-exporter/node_modules/hap-node-client/HAPNodeJSClient.js:115:10)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-prometheus-exporter/node_modules/hap-node-client/HAPNodeJSClient.js:191:7)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  [stack]: 'Error: Error checking type. Details: [invalid_union] Invalid input at path "accessories.accessories.[12].services.[1].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[1].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":11,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":15,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":19,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":23,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":27,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[23].services.[1].characteristics.[0]" (data at resolved path "accessories.accessories.[23].services.[1].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":11,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}")\n' +
    '    at checkBoundary (/usr/local/lib/node_modules/homebridge-prometheus-exporter/src/boundaries/checker.ts:51:11)\n' +
    '    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-prometheus-exporter/src/adapters/discovery/hap_node_js_client.ts:34:51)\n' +
    '    at HAPNodeJSClient.emit (node:events:390:28)\n' +
    '    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-prometheus-exporter/node_modules/hap-node-client/HAPNodeJSClient.js:115:10)\n' +
    '    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-prometheus-exporter/node_modules/hap-node-client/HAPNodeJSClient.js:191:7)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)',
  [message]: 'Error checking type. Details: [invalid_union] Invalid input at path "accessories.accessories.[12].services.[1].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[1].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":11,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":15,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":19,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":23,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[12].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[12].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":27,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[18].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[18].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[19].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[19].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[2].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[2].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":12,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[3].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[3].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":16,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[4].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[4].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":20,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[5].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[5].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":24,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[20].services.[6].characteristics.[0]" (data at resolved path "accessories.accessories.[20].services.[6].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":28,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]}") | [invalid_union] Invalid input at path "accessories.accessories.[23].services.[1].characteristics.[0]" (data at resolved path "accessories.accessories.[23].services.[1].characteristics.[0]" is "{"type":"00000073-0000-1000-8000-0026BB765291","iid":11,"value":null,"perms":["ev","pr"],"description":"Programmable Switch Event","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0]}")'
}
```

**Plugin Config:**

```json
        {
            "pin": "...",
            "debug": false,
            "prefix": "homebridge",
            "port": 36123,
            "refresh_interval": 60,
            "request_timeout": 10,
            "discovery_timeout": 20,
            "platform": "PrometheusExporter",
            "_bridge": {
                "username": "...",
                "port": 31344
            }
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**:  1.5.1
* **Node.js Version**:  v16.13.1
* **NPM Version**:  8.1.2
* **Operating System**:  Mac OS X 10.13.6

**Comment by lstrojny** [comment]
Thanks for bug report. I didn’t take into account that `characteristic.value` could also be null (not just non-existent or the actual type). Version 0.0.10 has just been release that includes a fix for it.
