### ISSUE TITLE
HAP discovery error Error: Could not resolve UUID 00000012-0000-1000-8000-656261617577 to service

### ISSUE THREAD

**Issue by frequentsailor** [lstrojny/homebridge-prometheus-exporter#9]
**Describe The Bug:**
After starting homebridge the error message mentioned under "Logs" is displayed. When browsing to /metrics the message "Metrics discovery pending" is displayed.

**To Reproduce:**
Install and configure plugin. Restart homebridge.

**Expected behavior:**
No error message and metrics exposed at /metrics.

**Logs:**
```
[09/11/2022, 13:15:51] [PrometheusExporter] HAP discovery error Error: Could not resolve UUID 00000012-0000-1000-8000-656261617577 to service
    at uuidToServerName (/usr/lib/node_modules/homebridge-prometheus-exporter/src/metrics.ts:140:11)
    at aggregate (/usr/lib/node_modules/homebridge-prometheus-exporter/src/metrics.ts:51:37)
    at /usr/lib/node_modules/homebridge-prometheus-exporter/src/platform.ts:58:42
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxx",
        "port": 51090,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "red",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "deCONZ",
            "anyOn": true,
            "configuredName": true,
            "effects": true,
            "hosts": [
                "192.168.1.3:8081"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "sensors": true,
            "users": {
                "xxx": "xxx"
            },
            "platform": "Hue"
        },
        {
            "name": "Miele@home",
            "clientID": "xxx",
            "clientSecret": "xxx",
            "language": "de",
            "reconnectEventServerInterval": 60,
            "disableStopActionFor": [
                "Dishwasher"
            ],
            "platform": "Miele@home"
        },
        {
            "name": "Shelly",
            "username": "xxx",
            "password": "xxx",
            "admin": {
                "enabled": true
            },
            "devices": [
                {
                    "id": "xxx",
                    "name": "Wohnzimmer Decke",
                    "type": "switch"
                },
                {
                    "id": "xxx",
                    "name": "Arbeitszimmer",
                    "type": "valve",
                    "exclude": false
                }
            ],
            "platform": "Shelly"
        },
        {
            "pin": "031-45-154",
            "debug": false,
            "prefix": "homebridge",
            "port": 36123,
            "refresh_interval": 60,
            "request_timeout": 10,
            "discovery_timeout": 20,
            "platform": "PrometheusExporter"
        }
    ],
    "accessories": [
        {
            "name": "Pihole",
            "auth": "xxx",
            "ssl": false,
            "rejectUnauthorized": true,
            "host": "192.168.1.3",
            "port": 80,
            "baseDirectory": "/admin/",
            "time": 0,
            "reversed": false,
            "logLevel": 1,
            "accessory": "Pihole"
        },
        {
            "accessory": "PhilipsTV",
            "name": "TV Wohnzimmer",
            "ip_address": "192.168.1.124",
            "poll_status_interval": "60",
            "model_year": 2016,
            "has_ssl": true,
            "has_ambilight": false,
            "wol_url": "wol://54:2A:A2:FA:B7:2E",
            "username": "xxx",
            "password": "xxx"
        },
        {
            "accessory": "mi-flower-care",
            "name": "Blumenkasten rechts",
            "deviceId": "xxx",
            "interval": 60
        },
        {
            "accessory": "mi-flower-care",
            "name": "Blumenkasten links",
            "deviceId": "xxx",
            "interval": 60
        }
    ],
    "disabledPlugins": [
        "homebridge-mieleathome",
        "homebridge-notification",
        "homebridge-mi-flower-care"
    ]
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v.0.0.4
* **Homebridge Version**: v1.5.1
* **Node.js Version**: v18.12.1
* **NPM Version**: v8.19.2
* **Operating System**: Raspbian

**Comment by lstrojny** [comment]
The error means that we got a service UUID that is not defined in the HomeKit spec. So far so good. The strange thing is, if I google the UUID or look it up on GitHub, I can only find spurious mentions but nothing definitive what it could be. So my plan right now is to assume it’s some sort of custom, non-standard service and handle it gracefully but that’s all I can do.

**Comment by lstrojny** [comment]
Bugfix landed, doing the release dance

**Comment by lstrojny** [comment]
0.0.5 published, please try again

**Comment by frequentsailor** [comment]
Perfect. Now I get the metrics exposed. Thank you very much for your effort and the quick fixes!

**Comment by lstrojny** [comment]
Terrific, thank you for the bug reports and your patience. When local assumptions hit reality it can be a bit bumpy.
